ATTACK_TYPES = {
    "Credential Phishing": {
        "what": "A deceptive attempt to steal usernames, passwords, or authentication tokens.",
        "how_attackers_do_it": "Attackers send fraudulent emails or create fake login portals that mimic trusted services (like banks or Microsoft 365).",
        "what_they_steal": "Login credentials, session cookies, and multi-factor authentication (MFA) tokens.",
        "who_is_targeted": "Employees, consumers, and high-value targets with access to sensitive systems.",
        "how_it_spreads": "Usually delivered via email, SMS (smishing), or direct messaging platforms.",
        "why_dangerous": "Once credentials are stolen, attackers can impersonate the victim, bypass security controls, and move laterally across networks."
    },
    "Business Email Compromise": {
        "what": "A targeted scam where attackers compromise or spoof legitimate business email accounts to conduct unauthorized wire transfers.",
        "how_attackers_do_it": "They impersonate executives or vendors and send urgent emails requesting immediate payment to fraudulent bank accounts.",
        "what_they_steal": "Financial assets and sensitive corporate data.",
        "who_is_targeted": "Finance departments, executives, and HR personnel.",
        "how_it_spreads": "Via spear-phishing or by compromising an internal account and replying to existing email threads.",
        "why_dangerous": "It relies on social engineering rather than malware, making it hard for traditional security tools to detect. It causes massive financial losses."
    },
    "Fake Login Page": {
        "what": "A fraudulent website designed to look exactly like a legitimate authentication portal.",
        "how_attackers_do_it": "They clone the HTML/CSS of services like PayPal, Office 365, or banking sites, and host them on lookalike domains.",
        "what_they_steal": "Usernames, passwords, and security question answers.",
        "who_is_targeted": "Users of popular online services and corporate single sign-on (SSO) portals.",
        "how_it_spreads": "Distributed via phishing emails, malvertising, or SMS.",
        "why_dangerous": "They are visually indistinguishable from the real sites, easily deceiving users into submitting their credentials."
    },
    "Brand Impersonation": {
        "what": "An attack where a malicious actor pretends to be a well-known brand or organization.",
        "how_attackers_do_it": "They register domains similar to the target brand (e.g., paypa1.com) and send communications mimicking the brand's style.",
        "what_they_steal": "Customer trust, credentials, and financial information.",
        "who_is_targeted": "Customers of the impersonated brand and the general public.",
        "how_it_spreads": "Phishing emails, fake social media accounts, and rogue mobile apps.",
        "why_dangerous": "It damages the brand's reputation and exploits the inherent trust users place in familiar organizations."
    },
    "DGA Generated Domain": {
        "what": "A domain name dynamically generated by malware using a Domain Generation Algorithm (DGA).",
        "how_attackers_do_it": "Malware uses algorithms to generate thousands of random-looking domains (e.g., xqjfz12.com) and attempts to connect to them to receive commands.",
        "what_they_steal": "Used to establish command and control (C2) communication to exfiltrate data or deploy further malware.",
        "who_is_targeted": "Infected systems across any industry.",
        "how_it_spreads": "Not an infection vector itself, but a technique used by botnets and ransomware to maintain communication.",
        "why_dangerous": "It makes it extremely difficult for defenders to block malicious communications, as the domains change rapidly."
    },
    "Suspicious Newly Registered Domain": {
        "what": "A domain name that has been registered very recently (typically within the last 30-90 days).",
        "how_attackers_do_it": "Attackers register new domains just before launching a phishing or spam campaign to bypass reputation-based filters.",
        "what_they_steal": "Used as infrastructure to host malware, phishing pages, or spam operations.",
        "who_is_targeted": "Broadly targeted via spam or targeted attacks.",
        "how_it_spreads": "Links are distributed via email or social media shortly after registration.",
        "why_dangerous": "Security vendors have no historical data on these domains, meaning they often bypass initial security filters."
    },
    "Malware Distribution": {
        "what": "The act of delivering malicious software (malware) to a target system.",
        "how_attackers_do_it": "Through malicious email attachments, drive-by downloads on compromised websites, or trojanized software.",
        "what_they_steal": "Data (spyware), computing resources (cryptojackers), or system access (ransomware).",
        "who_is_targeted": "Anyone. Broad campaigns target consumers, while APTs target specific organizations.",
        "how_it_spreads": "Spam campaigns, compromised websites, USB drives, or lateral movement within a network.",
        "why_dangerous": "Can lead to complete system compromise, data theft, or destructive ransomware attacks."
    },
    "Scareware": {
        "what": "Malicious software or web pop-ups that trick users into believing their computer is infected or compromised.",
        "how_attackers_do_it": "They display alarming, fake security warnings that prompt the user to download fake antivirus software or call a support number.",
        "what_they_steal": "Money (selling fake software) or credit card details.",
        "who_is_targeted": "Non-technical users and the elderly.",
        "how_it_spreads": "Malicious advertisements (malvertising) and compromised websites.",
        "why_dangerous": "Uses psychological manipulation (fear) to bypass rational decision-making."
    },
    "Tech Support Scam": {
        "what": "A fraud scheme where attackers claim to provide technical support to resolve a non-existent computer issue.",
        "how_attackers_do_it": "They use cold calls or scareware pop-ups to convince victims to grant them remote access to their computer.",
        "what_they_steal": "Financial information (charging for fake services) or the installation of actual malware.",
        "who_is_targeted": "General consumers, often targeting the elderly.",
        "how_it_spreads": "Pop-up ads, fake search engine results, and unsolicited phone calls.",
        "why_dangerous": "Victims willingly grant attackers full remote access to their machines."
    },
    "QRishing": {
        "what": "Phishing attacks conducted via malicious QR codes (Quishing).",
        "how_attackers_do_it": "They place fake QR codes on parking meters, restaurant menus, or in emails that direct users to phishing sites.",
        "what_they_steal": "Credentials or payment information (e.g., fake payment portals).",
        "who_is_targeted": "Mobile users.",
        "how_it_spreads": "Physical tampering (stickers over real QR codes) or digital distribution via email.",
        "why_dangerous": "Security tools often cannot scan the physical or image-based QR codes, bypassing email and web filters."
    },
    "Social Engineering": {
        "what": "The psychological manipulation of people into performing actions or divulging confidential information.",
        "how_attackers_do_it": "By exploiting human emotions like fear, curiosity, greed, or a desire to help.",
        "what_they_steal": "Information, credentials, or physical access.",
        "who_is_targeted": "Anyone with access to valuable information or systems.",
        "how_it_spreads": "Email, phone calls, social media, or in-person interactions.",
        "why_dangerous": "It exploits the weakest link in the security chain—humans—bypassing technical controls."
    },
    "Domain Spoofing": {
        "what": "An attack where a malicious actor uses a forged domain name to deceive users into believing they are interacting with a legitimate entity.",
        "how_attackers_do_it": "They use techniques like typosquatting or homograph attacks to make a domain look identical to a trusted one.",
        "what_they_steal": "Credentials, financial data, or used to distribute malware.",
        "who_is_targeted": "Users of the spoofed domain.",
        "how_it_spreads": "Phishing emails and malicious links.",
        "why_dangerous": "It leverages the trust users have in the legitimate domain."
    }
}

MITRE_MAPPINGS = {
    "Credential Phishing": [
        {"technique_id": "T1566.002", "technique_name": "Phishing: Spearphishing Link", "tactic": "Initial Access", "url": "https://attack.mitre.org/techniques/T1566/002/"},
        {"technique_id": "T1056.003", "technique_name": "Input Capture: Web Portal Capture", "tactic": "Credential Access", "url": "https://attack.mitre.org/techniques/T1056/003/"}
    ],
    "Business Email Compromise": [
        {"technique_id": "T1566.001", "technique_name": "Phishing: Spearphishing Attachment", "tactic": "Initial Access", "url": "https://attack.mitre.org/techniques/T1566/001/"},
        {"technique_id": "T1098", "technique_name": "Account Manipulation", "tactic": "Persistence", "url": "https://attack.mitre.org/techniques/T1098/"}
    ],
    "Fake Login Page": [
        {"technique_id": "T1056.003", "technique_name": "Input Capture: Web Portal Capture", "tactic": "Credential Access", "url": "https://attack.mitre.org/techniques/T1056/003/"}
    ],
    "Brand Impersonation": [
        {"technique_id": "T1583.001", "technique_name": "Acquire Infrastructure: Domains", "tactic": "Resource Development", "url": "https://attack.mitre.org/techniques/T1583/001/"}
    ],
    "DGA Generated Domain": [
        {"technique_id": "T1568.002", "technique_name": "Dynamic Resolution: Domain Generation Algorithms", "tactic": "Command and Control", "url": "https://attack.mitre.org/techniques/T1568/002/"}
    ],
    "Suspicious Newly Registered Domain": [
        {"technique_id": "T1583.001", "technique_name": "Acquire Infrastructure: Domains", "tactic": "Resource Development", "url": "https://attack.mitre.org/techniques/T1583/001/"}
    ],
    "Malware Distribution": [
        {"technique_id": "T1588.001", "technique_name": "Obtain Capabilities: Malware", "tactic": "Resource Development", "url": "https://attack.mitre.org/techniques/T1588/001/"},
        {"technique_id": "T1189", "technique_name": "Drive-by Compromise", "tactic": "Initial Access", "url": "https://attack.mitre.org/techniques/T1189/"}
    ],
    "Scareware": [
        {"technique_id": "T1490", "technique_name": "Inhibit System Recovery", "tactic": "Impact", "url": "https://attack.mitre.org/techniques/T1490/"}
    ],
    "Tech Support Scam": [
        {"technique_id": "T1566", "technique_name": "Phishing", "tactic": "Initial Access", "url": "https://attack.mitre.org/techniques/T1566/"}
    ],
    "QRishing": [
        {"technique_id": "T1566.002", "technique_name": "Phishing: Spearphishing Link", "tactic": "Initial Access", "url": "https://attack.mitre.org/techniques/T1566/002/"}
    ],
    "Social Engineering": [
        {"technique_id": "T1566", "technique_name": "Phishing", "tactic": "Initial Access", "url": "https://attack.mitre.org/techniques/T1566/"}
    ],
    "Domain Spoofing": [
        {"technique_id": "T1583.001", "technique_name": "Acquire Infrastructure: Domains", "tactic": "Resource Development", "url": "https://attack.mitre.org/techniques/T1583/001/"}
    ]
}

PREVENTION_PLAYBOOKS = {
    "default": {
        "what_to_do": ["Verify the sender's identity through a secondary channel.", "Inspect URLs carefully before clicking.", "Use strong, unique passwords for all accounts."],
        "what_not_to_do": ["Do not click on unsolicited links.", "Do not download attachments from unknown sources.", "Do not share sensitive information via email."],
        "immediate_actions": ["Delete the suspicious email or close the webpage.", "Report the incident to your IT security team."],
        "long_term_recommendations": ["Enable Multi-Factor Authentication (MFA).", "Participate in security awareness training."],
        "best_practices": ["Keep software and operating systems updated.", "Use a reputable password manager."]
    },
    "Credential Phishing": {
        "what_to_do": ["Enable MFA on all critical accounts.", "Verify the domain name in the address bar before entering credentials."],
        "what_not_to_do": ["Do not trust urgent requests for password resets or account verification.", "Do not reuse passwords across multiple services."],
        "immediate_actions": ["Block the sender's domain.", "Report the phishing attempt to the targeted brand."],
        "long_term_recommendations": ["Implement FIDO2 hardware security keys.", "Deploy email security gateways to filter phishing emails."],
        "best_practices": ["Regularly monitor account activity for unauthorized access.", "Use password managers to avoid typing credentials on fake sites."]
    },
    "Business Email Compromise": {
        "what_to_do": ["Verify all payment instructions via a known phone number.", "Establish a strict approval process for wire transfers."],
        "what_not_to_do": ["Do not process wire transfers based solely on an email request.", "Do not bypass established financial procedures."],
        "immediate_actions": ["Contact the bank immediately if a fraudulent transfer has occurred.", "Lock down the compromised email account."],
        "long_term_recommendations": ["Implement DMARC, SPF, and DKIM to prevent email spoofing.", "Conduct regular BEC simulation training for finance staff."],
        "best_practices": ["Use out-of-band communication for financial authorizations.", "Flag external emails with a warning banner."]
    }
}

INCIDENT_RESPONSE = {
    "default": {
        "containment": ["Isolate the affected device from the network.", "Block malicious IP addresses and domains at the firewall."],
        "recovery": ["Run a full antivirus scan.", "Restore systems from known good backups if compromised."],
        "reporting": ["Document the incident timeline and actions taken.", "Report to the internal security team or SOC."],
        "credential_reset": ["Reset passwords for any accounts suspected of being compromised."],
        "device_isolation": False,
        "browser_cleanup": ["Clear browser cache and cookies.", "Remove unauthorized browser extensions."],
        "enable_mfa": True
    },
    "Credential Phishing": {
        "containment": ["Force an immediate logout of all active sessions for the compromised user.", "Block the phishing URL on web gateways."],
        "recovery": ["Audit recent account activity for unauthorized changes.", "Revert any unauthorized inbox rules (e.g., auto-forwarding)."],
        "reporting": ["Notify affected users and provide guidance.", "Report the phishing site to safe browsing lists (e.g., Google Safe Browsing)."],
        "credential_reset": ["Mandate an immediate password reset for the compromised account.", "Reset credentials for related or reused accounts."],
        "device_isolation": False,
        "browser_cleanup": ["Clear saved passwords in the browser."],
        "enable_mfa": True
    },
    "Malware Distribution": {
        "containment": ["Immediately disconnect the infected machine from the network (wired and wireless).", "Disable switch ports if necessary."],
        "recovery": ["Wipe and reimage the infected machine.", "Restore user data from offline backups."],
        "reporting": ["Report the malware hash to threat intelligence platforms.", "Notify legal/compliance if data exfiltration is suspected."],
        "credential_reset": ["Reset all passwords that were cached or used on the infected machine."],
        "device_isolation": True,
        "browser_cleanup": ["Clear all browser data and temporary files."],
        "enable_mfa": True
    }
}
